apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-primary
  namespace: 7tv
  labels:
    name: redis-primary
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: redis-primary
  template:
    metadata:
      labels:
        name: redis-primary
    spec:
      containers:
      - name: redis
        image: redis:6-alpine
        resources:
          requests:
            memory: "25Mi"
            cpu: "15m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /redis
            name: config
        command:
          - "redis-server"
        env:
          - name: CLUSTER_CONFIG
            value: /redis/redis.conf
        args:
          - '/redis/redis.conf'
        ports:
        - containerPort: 6379
      volumes:
        - name: config
          configMap:
            name: redis-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    cluster-enabled no
    protected-mode no

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis-primary
  ports:
  - port: 6379
    targetPort: 6379

---

# Redsmin Proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-redsmin
  labels:
    name: redis-redsmin
spec:
  selector:
    matchLabels:
      name: redis-redsmin
  template:
    metadata:
      labels:
        name: redis-redsmin
    spec:
      containers:
      - name: redis-redsmin
        image: redsmin/proxy
        env:
          - name: REDIS_URI
            value: "redis.7tv.svc.cluster.local"
          - name: REDSMIN_KEY
            value: "6058cedc10d5f5102d816e85"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-redsmin-svc
spec:
  selector:
    name: redis-redsmin
  ports:
  - port: 6379
    targetPort: 6379

