apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: 7tv
  name: can-deploy-7tv
rules:
  - apiGroups: ["", "extensions", "apps"]
    verbs: ["get", "patch"] # Only allow patching the resources (for using the rollout command)
    resources: ["deployments", "statefulsets", "services"]
    # resourceNames: ["7tv-nodeapi", "7tv-goapi", "7tv-webapp"] # Only the defined deployables

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: 7tv
  name: can-deploy-7tv-bind

subjects:
  - name: 7tv-deployer
    kind: ServiceAccount
    namespace: 7tv
roleRef:
  kind: Role
  name: can-deploy-7tv
  apiGroup: rbac.authorization.k8s.io