apiVersion: v1
kind: Pod
metadata:
  name: docker-pod
  namespace: default
  labels:
    name: docker-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: docker-pod
      image: docker
      volumeMounts:
        - name: daemon-config
          mountPath: "/etc/docker/daemon.json"
          subPath: daemon.json
          readOnly: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      command: ["sh", "-c", "--"]
      args: ["while true; do sleep 5; done;"]

  volumes:
    - name: daemon-config
      configMap:
        name: dockerpod-config
        items:
          - key: daemon.json
            path: daemon.json

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerpod-config
  namespace: default
data:
  daemon.json: |
    { "insecure-registries":["registry.7tv.app", "docker-registry.docker-registry.svc.cluster.local:5000"] }
