name: Build System Image

env:
  IMAGE_TAG: ghcr.io/seventv/server/system

on:
  workflow_dispatch:
    inputs:
      version:
        description: Image Version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build System Image
        run: docker build . --file Sys.Dockerfile --tag image

      - name: Sign In with the Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image
        run: |
          docker tag image $IMAGE_TAG
          docker push $IMAGE_TAG
